---

# Travis file for tox_docker_test_driven role

dist: 'trusty'
sudo: 'required'

services:
  - 'docker'

language: 'python'

python:
  - '2.7'

env:
  global:
    - ANSIBLE_ROLES_PATH="${TRAVIS_BUILD_DIR%/*/*}"

  matrix:
    - >
      TOXENV='py27-ansible19'
      DOCKER_IMAGE='ubuntu:14.04'
    - >
      TOXENV='py27-ansible19'
      DOCKER_IMAGE='ubuntu:16.04'
    - >
      TOXENV='py27-ansible20'
      DOCKER_IMAGE='ubuntu:14.04'
    - >
      TOXENV='py27-ansible20'
      DOCKER_IMAGE='ubuntu:16.04'
    - >
      TOXENV='py27-ansible21'
      DOCKER_IMAGE='ubuntu:14.04'
    - >
      TOXENV='py27-ansible21'
      DOCKER_IMAGE='ubuntu:16.04'
    - >
      TOXENV='py27-ansible-devel'
      DOCKER_IMAGE='ubuntu:14.04'
    - >
      TOXENV='py27-ansible-devel'
      DOCKER_IMAGE='ubuntu:16.04'

install:

  # Install tox dependency
  - 'pip install tox'

script:

  # Run tests
  - 'make test-env'

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
