---

# Travis file for tox_docker_test_driven role

dist: trusty
sudo: required

services:
  - docker

language: python

env:
  - ANSIBLE_ROLES_PATH="${TRAVIS_BUILD_DIR%/*/*}"
  - TOXENV=py27-ansible19
  - TOXENV=py27-ansible20
  - TOXENV=py27-ansible21
  - TOXENV=py27-ansible-devel

install:

  # Install tox dependency
  - pip install tox

script:

  # Run tests
  - make test

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
